version: '3'

services:
    mongodb:
        image: {{CONTAINER_MONGODB_IMAGE}}:{{CONTAINER_MONGODB_VERSION}}
        container_name: {{PROJECT_NAME}}_{{CONTAINER_MONGODB_NAME}}
        restart: on-failure:5
        mem_limit: 1024m
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./../sysdumps/mongodb:/data/db
        networks:
            - docker_projectsubnetwork

networks:
    docker_projectsubnetwork:
        external: true
